### ISSUE TITLE
A new version of Hamilton has been released

### ISSUE THREAD

**Issue by ngzhio** [Aspiring-Writer/aspiring-writer.github.io#1]
Hi, thank you again for using the Hamilton theme. A [new version](https://github.com/ngzhio/jekyll-theme-hamilton/releases/tag/v1.4.0) has been released, you can check out the [demo](https://ngzhio.github.io/jekyll-theme-hamilton/). More details can be found in this [post](https://ngzhio.github.io/2020/07/01/releasing-hamilton-1-4-0.html). Do you like this upgrade?

![homepage-on-desktopafter](https://user-images.githubusercontent.com/63144665/86247070-89f6ad00-bbde-11ea-8d55-21d91eafbf19.png)

**Comment by Aspiring-Writer** [comment]
I'm not sure if I like how the site author shows up on the side 🤔 I will have to play around with it when I have time. Thanks for asking!

**Comment by Aspiring-Writer** [comment]
I'm sorry but I have changed the theme for this site. I will keep Hamilton under my list of recommended themes for the next site that I create

**Comment by ngzhio** [comment]
It's OK. I'm frequently change themes too. Thank you to use Hamilton, any suggestion is welcome.
